### ISSUE TITLE
the program is blocked at startup

### ISSUE THREAD

**Issue by Finansvalp** [Baldhor/Homey-ESPhome-Enhanced#2] opened 2023-08-05 05:05 UTC
when you start Homeyn, there is a red triangle over the device. you have to restart the app for it to work again. 

this has come after the last update.

Another thing, it is not possible to set how many decimal places you want on the display. I have a Slimmelezer connected to the energy meter. 

Lars

**Comment by Baldhor** [comment] 2023-08-05 10:41
@Finansvalp hello, I think I received a report from you, can you confirm?

The problem appear everytime you restart homey ? Or it just happened once after upgrade to the new version?

**Comment by Baldhor** [comment] 2023-08-05 10:42
As about Slimmelezer, can you provide a screenshot of decimal issue?

**Comment by Finansvalp** [comment] 2023-08-05 10:49
*Hello *
*it happens every time i start the homey *
*lars*

lör 5 aug. 2023 kl. 12:41 skrev Baldhor ***@***.***>:

**Comment by Finansvalp** [comment] 2023-08-05 10:49
lör 5 aug. 2023 kl. 12:42 skrev Baldhor ***@***.***>:

**Comment by Baldhor** [comment] 2023-08-05 11:44
**1/ Connection**
The connection break in the middle, no idea why:
2023-08-05T04:55:04.407Z [log] [ManagerDrivers] [Driver:esphome-device] [Device:0cc0a11d-2a06-41b2-8ac2-816f8ae0c3d2] Error on device slimmelezer: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
2023-08-05T04:55:04.412Z [log] [ManagerDrivers] [Driver:esphome-device] [Device:0cc0a11d-2a06-41b2-8ac2-816f8ae0c3d2] Device slimmelezer disconnected

=> I need the log from your Slimmelezer device, connect to its webserver and collect it please.

**2/ Decimal issue**
Your device send very precise measure :
2023-08-05T04:54:38.899Z [log] [ManagerDrivers] [Driver:esphome-device] [Device:0cc0a11d-2a06-41b2-8ac2-816f8ae0c3d2] Setting measure_current.11 to 2.4000000953674316

=> Can you upload your device configuration ? You should be able to modifiy its configuration to reduce it

**Comment by Finansvalp** [comment] 2023-08-06 06:20
Slimmelezer working config report id: 0b07ba21-889d-4f36-b310-5df028e30188




lör 5 aug. 2023 kl. 13:44 skrev Baldhor ***@***.***>:

> *1/ Connection*
> The connection break in the middle, no idea why:
> 2023-08-05T04:55:04.407Z [log] [ManagerDrivers] [Driver:esphome-device]
> [Device:0cc0a11d-2a06-41b2-8ac2-816f8ae0c3d2] Error on device slimmelezer:
> Error: read ECONNRESET
> at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
> errno: -104,
> code: 'ECONNRESET',
> syscall: 'read'
> }
> 2023-08-05T04:55:04.412Z [log] [ManagerDrivers] [Driver:esphome-device]
> [Device:0cc0a11d-2a06-41b2-8ac2-816f8ae0c3d2] Device slimmelezer
> disconnected
>
> => I need the log from your Slimmelezer device, connect to its webserver
> and collect it please.
>
TimelevelTagMessage
18:25:09 [D] [sensor:126]

'Power Produced Phase 2': Sending state 1.20000 kW with 3 decimals of accuracy

18:25:09 [D] [sensor:126]

'Power Produced Phase 3': Sending state 1.19200 kW with 3 decimals of accuracy

18:25:14 [D] [sensor:126]

'Energy Consumed Luxembourg': Sending state 9954.75098 kWh with 3
decimals of accuracy

18:25:14 [D] [sensor:126]

'Energy Produced Luxembourg': Sending state 12448.50391 kWh with 3
decimals of accuracy

18:25:14 [D] [sensor:126]

'Power Consumed': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:14 [D] [sensor:126]

'Power Produced': Sending state 3.63100 kW with 3 decimals of accuracy

18:25:14 [D] [sensor:126]

'Voltage Phase 1': Sending state 233.70000 V with 1 decimals of accuracy

18:25:14 [D] [sensor:126]

'Voltage Phase 2': Sending state 233.80000 V with 1 decimals of accuracy

18:25:14 [D] [sensor:126]

'Voltage Phase 3': Sending state 233.89999 V with 1 decimals of accuracy

18:25:14 [D] [sensor:126]

'Current Phase 1': Sending state 5.70000 A with 1 decimals of accuracy

18:25:14 [D] [sensor:126]

'Current Phase 2': Sending state 5.70000 A with 1 decimals of accuracy

18:25:14 [D] [sensor:126]

'Current Phase 3': Sending state 5.60000 A with 1 decimals of accuracy

18:25:14 [D] [sensor:126]

'Power Consumed Phase 1': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:14 [D] [sensor:126]

'Power Consumed Phase 2': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:14 [D] [sensor:126]

'Power Consumed Phase 3': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:14 [D] [sensor:126]

'Power Produced Phase 1': Sending state 1.23300 kW with 3 decimals of accuracy

18:25:14 [D] [sensor:126]

'Power Produced Phase 2': Sending state 1.20400 kW with 3 decimals of accuracy

18:25:14 [D] [sensor:126]

'Power Produced Phase 3': Sending state 1.19300 kW with 3 decimals of accuracy

18:25:22 [D] [sensor:126]

'Energy Consumed Luxembourg': Sending state 9954.75098 kWh with 3
decimals of accuracy

18:25:23 [D] [sensor:126]

'Energy Produced Luxembourg': Sending state 12448.50879 kWh with 3
decimals of accuracy

18:25:23 [D] [sensor:126]

'Power Consumed': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:23 [D] [sensor:126]

'Power Produced': Sending state 3.64000 kW with 3 decimals of accuracy

18:25:23 [D] [sensor:126]

'Voltage Phase 1': Sending state 233.70000 V with 1 decimals of accuracy

18:25:23 [D] [sensor:126]

'Voltage Phase 2': Sending state 233.80000 V with 1 decimals of accuracy

18:25:23 [D] [sensor:126]

'Voltage Phase 3': Sending state 234.00000 V with 1 decimals of accuracy

18:25:23 [D] [sensor:126]

'Current Phase 1': Sending state 5.80000 A with 1 decimals of accuracy

18:25:23 [D] [sensor:126]

'Current Phase 2': Sending state 5.70000 A with 1 decimals of accuracy

18:25:23 [D] [sensor:126]

'Current Phase 3': Sending state 5.60000 A with 1 decimals of accuracy

18:25:23 [D] [sensor:126]

'Power Consumed Phase 1': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:23 [D] [sensor:126]

'Power Consumed Phase 2': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:23 [D] [sensor:126]

'Power Consumed Phase 3': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:23 [D] [sensor:126]

'Power Produced Phase 1': Sending state 1.23400 kW with 3 decimals of accuracy

18:25:23 [D] [sensor:126]

'Power Produced Phase 2': Sending state 1.20600 kW with 3 decimals of accuracy

18:25:23 [D] [sensor:126]

'Power Produced Phase 3': Sending state 1.19900 kW with 3 decimals of accuracy

18:25:27 [D] [sensor:126]

'Energy Consumed Luxembourg': Sending state 9954.75098 kWh with 3
decimals of accuracy

18:25:27 [D] [sensor:126]

'Energy Produced Luxembourg': Sending state 12448.51367 kWh with 3
decimals of accuracy

18:25:27 [D] [sensor:126]

'Power Consumed': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:27 [D] [sensor:126]

'Power Produced': Sending state 3.63600 kW with 3 decimals of accuracy

18:25:27 [D] [sensor:126]

'Voltage Phase 1': Sending state 233.80000 V with 1 decimals of accuracy

18:25:27 [D] [sensor:126]

'Voltage Phase 2': Sending state 233.70000 V with 1 decimals of accuracy

18:25:27 [D] [sensor:126]

'Voltage Phase 3': Sending state 234.10001 V with 1 decimals of accuracy

18:25:27 [D] [sensor:126]

'Current Phase 1': Sending state 5.80000 A with 1 decimals of accuracy

18:25:27 [D] [sensor:126]

'Current Phase 2': Sending state 5.70000 A with 1 decimals of accuracy

18:25:27 [D] [sensor:126]

'Current Phase 3': Sending state 5.60000 A with 1 decimals of accuracy

18:25:27 [D] [sensor:126]

'Power Consumed Phase 1': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:27 [D] [sensor:126]

'Power Consumed Phase 2': Sending state 0.00000 kW with 3 decimals of accuracy

18:25:27 [D] [sensor:126]

'Power Consumed Phase 3': Sending l
state 0.00000 kW with 3 decimals of accuracy

18:25:27 [D] [sensor:126]

'Power Produced Phase 1': Sending state 1.23400 kW with 3 decimals of accuracy

18:25:27 [D] [sensor:126]

'Power Produced Phase 2': Sending state 1.20300 kW with 3 decimals of accuracy

18:25:27 [D] [sensor:126]

'Power Produced Phase 3': Sending state 1.19700 kW with 3 decimals of accuracy


*2/ Decimal issue*

**Comment by Baldhor** [comment] 2023-08-06 10:23
@Finansvalp 
Looking at the code, the device should reconnect automatically after 30 seconds.

As for the decimals, the app already use the config received from the device.
The problem is that some of your sensors have a high configuration :
'Energy Consumed Luxembourg': Sending state 9954.75098 kWh with 3 decimals of accuracy

Up to you to configure it on your device, to do so you need to update your yaml configuration, recompile and upload:
https://esphome.io/components/sensor/

Please note that new values require to pair again your device!

**Comment by RoadXY** [comment] 2023-08-07 09:39
I also have a slimmemeter and changed the dsmr request interval to 30s.
Here is a snippet of the code:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/4e08bbe1-88c7-4193-849d-2be72b7334ec)

**Comment by Baldhor** [comment] 2023-08-07 12:48
@Finansvalp Can you try above configuration ?

As for the decimal issue, refer to #9.

**Comment by Finansvalp** [comment] 2023-08-07 13:09
Hello I went to homey web and there Slimmelezern shows the correct values
​​with 2-3 decimal places. Then there must be an error with the Homey app.
Lars

mån 7 aug. 2023 kl. 14:48 skrev Baldhor ***@***.***>:

**Comment by Baldhor** [comment] 2023-08-08 08:17
> 

@Finansvalp decimals issue is solved refer to #9. Let's focus on your stability issue :) Can you try RoadXY suggestion?
You can also try to use console.re to collect more logs: https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/ConsoleRe-support

**Comment by Baldhor** [comment] 2023-08-08 16:33
@Finansvalp [console.re/Slimmelezer](https://console.re/Slimmelezer) is empty, I really think it is your physical device crashing.
I published a new version ensure we can see what happen at start of the application in console.re.
Please, install: https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

You should look at your device webserver too, in the meantime, I will keep the console.re/Slimmelezer window open.

**Comment by Baldhor** [comment] 2023-08-17 14:32
no news, closing

**Closed by Baldhor** 2023-08-17 14:32 UTC
Labels: question
