### ISSUE TITLE
[BUG] Latest Homey update app unavailable error messages

### ISSUE THREAD

**Issue by Dest1n7** [Baldhor/Homey-ESPhome-Enhanced#70] opened 2023-10-23 12:49 UTC
Since the latest homey update (earlier today) the devices have error messages reading “app unavailable”.

**Comment by Baldhor** [comment] 2023-10-23 13:04
Can you retrieve the log info for the physical device concerned ?

From the manage your physical devices page in the wizard.

I'm sorry for the issue, looking at it I believe youu are not alone with
this issue

**Comment by Baldhor** [comment] 2023-10-23 13:11
Reading it again, the app doesn't even start correctly!

Damn it, I can't do anything from work .. need wait a few hours for a fix.

**Comment by Baldhor** [comment] 2023-10-23 13:34
Ok so I found the issue, I added a piece of code to clean up the options of the capability.
Because of a past bug, it could contains null or empty ("") values ...

The problem now is that sometimes, a capability doesn't have any options ... and the getCapabilityOptions of Homey returns an "invalid capability" error.
This function is called in many places through the code, so I need to implement my own function which will catch the error and returns an empty object (instead of an error) ... then modify all the code to call the new function instead of the Homey one ...

Like 10 minutes to fix and test ...

**But I need my computer to do so.**

I will publish the fix in about 4/5 hours (cannot from work).

**Comment by Baldhor** [comment] 2023-10-23 13:34
@Dest1n7 see above, sorry for the inconvenience

**Comment by Baldhor** [comment] 2023-10-23 19:16
I cannot reproduce it, my setup imply that capabilities always have options ...

I still made a fix, and verified that it doesn't make new issue ...

@Dest1n7 Sorry for it, but please can you check if it fix the issue ? => https://tools.developer.homey.app/apps/app/nl.inversion.esphome/build/75

**Comment by Dest1n7** [comment] 2023-10-24 04:38
Good morning @Baldhor everything seems to work again after the latest update. Thank you so so much for the super quick turnaround!!!

**Comment by Baldhor** [comment] 2023-10-24 07:55
Closing

**Closed by Baldhor** 2023-10-24 07:55 UTC
